### Variables
# @baseUrl = http://tms.dev/api/user
@baseUrl = http://localhost:4001
@accessToken = {{login.response.body.access_token}}

###
### User Auth Endpoints
###


### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "yaser-alazm",
  "email": "yaser@example.com",
  "password": "Password123!",
  "firstName": "Yaser",
  "lastName": "Alazm",
  "roles": ["admin"]
}

### Login
## usernames: admin, testuser, yaser-az
## passwords: Password123!
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "yaser-az",
  "password": "Password123!"
}

### Get Profile (Protected)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}

### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "test2@example.com"
}

### Change Password
POST {{baseUrl}}/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "Password123!",
  "newPassword": "NewPassword456!"
}

###
### Users Endpoints
###

### Get All Users
GET {{baseUrl}}/
Authorization: Bearer {{accessToken}}

### Get User by ID
GET {{baseUrl}}/2f23ef01-5ca4-462a-be6c-248eaf9be959
Authorization: Bearer {{accessToken}}

### Create New User
POST {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "john-doe",
  "email": "john.doe@example.com",
  "password": "Password123!",
  "firstName": "John",
  "lastName": "Doe",
  "roles": ["user"]
}

### Update User
PUT {{baseUrl}}/a01ad4d9-f830-42cf-9d91-62c5a5d48d2f
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "yaser-alazm",
  "firstName": "Yasser",
  "roles": ["admin"]
}

### Delete User
DELETE {{baseUrl}}/1234-5678-9012
Authorization: Bearer {{accessToken}}

### Health Check
GET {{baseUrl}}/hello
Authorization: Bearer {{accessToken}}